# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhD Spotlight
# email: comunicazione@di.unipi.it
description: > # this means to ignore newlines until "baseurl:"
  PhD Spotlight - From Study to Research

#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#sidebar
default-image: /images/unavailable.png

#footer

built-by:

copyright:
  name: PhD Spotlight Team
  link: "mailto:comunicazione@di.unipi.it?subject=[PhD Spotlight] Request for information"

# Build settings
permalink: /:title/
paginate: 100
paginate_path: /page:num/

# Tracker

#social
# facebook: http://facebook.com/
# quora: http://quora.com/
# twitter: http://twitter.com/
github: https://github.com/phd-spotlight

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - favicon.ico
  - Gemfile
  - Gemfile.lock
  - Gemfile.local
  - Gemfile.github
  - Makefile
  - README.md
  - INSTALL.md
  - LICENSE
  - .github/
  - .gitignore
  - pdf-to-png.sh
